# Generated by Django 3.1.4 on 2020-12-02 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('profiles', '0005_auto_20190723_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.site'),
        ),
    ]
