# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-13 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20190723_1808'),
        ('profiles', '0005_auto_20191014_0959'),
    ]

    operations = [
    ]
