# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-13 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_merge_20191113_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilessettings',
            name='require_login',
            field=models.BooleanField(default=False, help_text='Require login to access site content', verbose_name='Require login'),
        ),
    ]
