# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-01 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_add_show_security_question_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilessettings',
            name='num_security_questions',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Number of security questions asked for password recovery'),
        ),
        migrations.AddField(
            model_name='userprofilessettings',
            name='password_recovery_retries',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Max number of password recovery retries before lockout'),
        ),
    ]
