# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-17 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_add_curent_site_to_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fcm_registration_token',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
