# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-05 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_can_view_response_reaction_question_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepage',
            options={'ordering': ('-latest_revision_created_at',), 'verbose_name': 'Article'},
        ),
        migrations.AddField(
            model_name='articlepage',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SiteLanguage'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='translated_pages',
            field=models.ManyToManyField(blank=True, null=True, related_name='_articlepage_translated_pages_+', to='core.ArticlePage'),
        ),
    ]
