# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-05 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_new_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SiteLanguage'),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='translated_pages',
            field=models.ManyToManyField(blank=True, null=True, related_name='_sectionpage_translated_pages_+', to='core.SectionPage'),
        ),
    ]
