# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-09 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180906_0915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepage',
            options={'ordering': ('-latest_revision_created_at',), 'verbose_name': 'Article'},
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_service_directory_radius',
            field=models.PositiveSmallIntegerField(blank=True, help_text='When set this will enable service directory radius filter as the set value for the default radius value', null=True, verbose_name='Default Service Directory Radius'),
        ),
    ]
