# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-22 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_viber_sharing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepage',
            old_name='feature_as_topic_of_the_day',
            new_name='feature_as_hero_article',
        ),
    ]
