# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_email_to_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='article_ordering',
            field=models.SmallIntegerField(choices=[(1, ('CMS Ordering', 'sort_order')), (2, ('CMS Ordering Desc', '-sort_order')), (3, ('First Published Date', 'first_published_at')), (4, ('First Published Date Desc', '-first_published_at'))], null=True),
        ),
    ]
