# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_email_to_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='article_ordering',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'CMS Default Sorting'), (2, 'first_published_at'), (3, '-first_published_at'), (4, 'pk'), (5, '-pk')], null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='section_ordering',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'CMS Default Sorting'), (2, 'featured_in_section_start_date'), (3, '-featured_in_section_start_date'), (4, 'first_published_at'), (5, '-first_published_at'), (6, 'pk'), (7, '-pk')], null=True),
        ),
    ]
