# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 11:21
from __future__ import unicode_literals

from django.db import migrations
import django_enumfield.db.fields
import molo.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_email_to_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='article_ordering',
            field=django_enumfield.db.fields.EnumField(blank=True, default=1, enum=molo.core.models.ArticleOrderingChoices, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='section_ordering',
            field=django_enumfield.db.fields.EnumField(blank=True, default=1, enum=molo.core.models.SectionOrderingChoices, null=True),
        ),
    ]
