# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-08 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_email_to_forms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoloPage',
        ),
    ]
