# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-15 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sitesettings_article_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='section_ordering',
            field=models.SmallIntegerField(choices=[(1, 'featured_in_section_start_date'), (2, '-featured_in_section_start_date')], null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='article_ordering',
            field=models.SmallIntegerField(choices=[(1, 'sort_order'), (2, '-sort_order'), (3, 'first_published_at'), (4, '-first_published_at')], null=True),
        ),
    ]
