# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-21 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django_enumfield.db.fields
import molo.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sitesettings_article_ordering_within_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerpage',
            name='hide_banner_on_freebasics',
            field=models.BooleanField(default=False),
        )
    ]
