# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-15 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190415_0743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerpage',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='articlepage',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='article_ordering',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'first_published_at'), (2, '-first_published_at'), (3, 'pk'), (4, '-pk'), (5, 'sort_order'), (6, '-sort_order')], null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='section_ordering',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'featured_in_section_start_date'), (2, '-featured_in_section_start_date'), (3, 'first_published_at'), (4, '-first_published_at'), (5, 'pk'), (6, '-pk'), (7, 'sort_order'), (8, '-sort_order')], null=True),
        ),
    ]
