# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-14 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_wagtail_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='is_service_aggregator',
            field=models.BooleanField(default=False, verbose_name='Service aggregator'),
        )
    ]
