# Generated by Django 2.2.7 on 2020-03-27 05:40

from django.db import migrations, models
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('core', '0019_add_is_service_aggregator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reactionquestion',
            name='language',
        ),
        migrations.RemoveField(
            model_name='reactionquestion',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='reactionquestion',
            name='translated_pages',
        ),
        migrations.RemoveField(
            model_name='reactionquestionchoice',
            name='image',
        ),
        migrations.RemoveField(
            model_name='reactionquestionchoice',
            name='language',
        ),
        migrations.RemoveField(
            model_name='reactionquestionchoice',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='reactionquestionchoice',
            name='success_image',
        ),
        migrations.RemoveField(
            model_name='reactionquestionchoice',
            name='translated_pages',
        ),
        migrations.RemoveField(
            model_name='reactionquestionindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='reactionquestionresponse',
            name='article',
        ),
        migrations.RemoveField(
            model_name='reactionquestionresponse',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='reactionquestionresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='reactionquestionresponse',
            name='user',
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='metadata_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags. This is not visible to the user.', related_name='metadata_tags', through='core.ArticlePageMetaDataTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='sitelanguage',
            name='locale',
            field=models.CharField(choices=[('af', 'Afrikaans'), ('ar', 'Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kab', 'Kabyle'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('th', 'Thai'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese'), ('zu', 'Zulu'), ('xh', 'Xhosa'), ('st', 'Sotho'), ('ve', 'Venda'), ('tn', 'Tswana'), ('ts', 'Tsonga'), ('ss', 'Swati'), ('nr', 'Ndebele')], help_text='Site language', max_length=255, verbose_name='language name'),
        ),
        migrations.DeleteModel(
            name='ArticlePageReactionQuestions',
        ),
        migrations.DeleteModel(
            name='ReactionQuestion',
        ),
        migrations.DeleteModel(
            name='ReactionQuestionChoice',
        ),
        migrations.DeleteModel(
            name='ReactionQuestionIndexPage',
        ),
        migrations.DeleteModel(
            name='ReactionQuestionResponse',
        ),
    ]
