# Generated by Django 3.1.5 on 2021-01-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20201215_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='article_ordering_within_section',
            field=models.TextField(blank=True, choices=[('cms_default_sorting', 'CMS Default Sorting'), ('first_published_at', 'First Published At'), ('first_published_at_desc', 'First Published At Desc'), ('pk', 'Primary Key'), ('pk_desc', 'Primary Key Desc')], default='cms_default_sorting', help_text='Ordering of articles within a section', null=True),
        ),
    ]
