# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_content_rotation_dates_and_times'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='f',
            new_name='friday',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='m',
            new_name='monday',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='sa',
            new_name='saturday',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='su',
            new_name='sunday',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='th',
            new_name='thursday',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='tu',
            new_name='tuesday',
        ),
        migrations.RenameField(
            model_name='sitesettings',
            old_name='w',
            new_name='wednesday',
        ),
    ]
