# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-02 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_add_topic_of_the_day_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerpage',
            name='external_link',
            field=models.TextField(blank=True, help_text=b'External link which a banner will link to. eg https://www.google.co.za/', null=True),
        ),
    ]
