# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-11 09:33
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_add_core_permissions_to_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='social_media',
            field=wagtail.wagtailcore.fields.StreamField([(b'social_media_site', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock(required=True)), (b'link', wagtail.wagtailcore.blocks.CharBlock(required=True)), (b'image', wagtail.wagtailimages.blocks.ImageChooserBlock())]))], blank=True, null=True),
        ),
    ]
