# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-23 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_add_social_media_links_to_site_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='featured_in_homepage_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='featured_in_latest_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='featured_in_section_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
