# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-08 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20170206_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitelanguage',
            options={'verbose_name': 'Language'},
        ),
    ]
