# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-06 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20170602_1713'),
        ('core', '0061_add_success_fields_to_reaction_choice'),
    ]

    operations = [
    ]
