# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-08 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20170606_1558'),
        ('core', '0062_increase_char_length_reaction_success'),
    ]

    operations = [
    ]
