# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-09-18 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_add_image_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
