buildscript: testapp/sideloader/build.sh
postinstall: testapp/sideloader/postinstall.sh
pip:
  - gunicorn
  - psycopg2
dependencies:
  - nginx
  - postgresql-server-dev-all
  - libpq-dev
  - libffi-dev
  - postgresql
  - redis-server
  - libjpeg-dev
  - zlib1g-dev
  - gettext
