name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine
        pip install -r requirements-dev.txt
        pip install flake8
        pip install -e .
    - name: Lint with flake8
      run: |
        flake8 molo --count --select=E9,F63,F7,F82 --max-complexity=20 --max-line-length=90 --statistics
        flake8 --config=molo/core/migrations/.flake8 molo/core/migrations/ --select=E9,F63,F7,F82
        flake8 --config=molo/profiles/migrations/.flake8 molo/profiles/migrations/ --select=E9,F63,F7,F82
    - name: Test with pytest
      run: |
        molo scaffold testapp
        mkdir -p testapp/testapp/templates/registration/
        cp molo/profiles/test_templates/login.html testapp/testapp/templates/registration/
        cp local_test_settings.py testapp/testapp/settings/local.py
        python testapp/manage.py runscript template_lint
        flake8 testapp
        pip install -e testapp
        py.test
